image: node:18

stages:
  - build

pages:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - yarn install
    - yarn generate
    # Optional: this gzips all files, so GitLab can serve compressed assets.
    # - gzip -k -6 $(find .output/public -type f)
  artifacts:
    paths:
      - .output/public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

