image: node:18-alpine

stages:
- before_script
- build

cache:
  paths:
  - node_modules/

before_script:
- apk add rsync
- yarn install
- yarn generate

pages:
  stage: build
  script:
  - rsync --del -r .output/public/ public
  - find public -type f -print0 | xargs -0r gzip -k -6
  artifacts:
    paths:
    - public
  rules:
  - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
