stages:
- build
- deploy

cache:
  - key:
      files:
        - yarn.lock
    paths:
      - node_modules/
    policy: pull-push

build:
  image: node:18-alpine
  stage: build

  before_script:  
    - | 
      if [ ! -d "node_modules" ]; then
        echo "Cache restoration failed. Recreating cache..."
        rm -rf node_modules/
        yarn install
      fi

  script:
    - yarn generate

  artifacts:
    paths:
      - .output/public/
    when: on-success

  rules:
    - changes:
        paths:
          - "{.gitlab-ci,package,app*,nuxt.config,tsconfig,yarn}.{yml,json,ts,vue,lock}"
          - "{assets,components,content,layouts,pages,plugins,public}/**/*"

pages:
  image: busybox:latest
  stage: deploy

  needs:
    - job: build
      artifacts: true

  script:
    - mv .output/public public
    - find public -type f -print0 | xargs -0r gzip -k -6

  artifacts:
    paths:
      - public

  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      needs: ['build']
      changes:
        paths:
          - "{.gitlab-ci,package,app*,nuxt.config,tsconfig,yarn}.{yml,json,ts,vue,lock}"
          - "{components,assets,content,layouts,pages,plugins,public}/**/*"
