# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: node:18-alpine
stages:
- before_script
- build
- test
cache:
  paths:
  - node_modules/
before_script:
- apk add rsync
- yarn install
- yarn generate
pages:
  stage: build
  script:
  - rsync --del -r .output/public/ public
  - find public -type f -print0 | xargs -0r gzip -k -6
  artifacts:
    paths:
    - public
  rules:
  - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
