image: node:18

stages:
  - before_script
  - build

cache:
  paths:
    - node_modules/

before_script:
  - apt install rsync
  - yarn install
  - yarn generate

pages:
  stage: build
  script: 
    - rsync --del .output/public/ public
    # Optional: this gzips all files, so GitLab can serve compressed assets.
    # - gzip -k -6 $(find public -type f)
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

